modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="backpack"
version="1.0.0"
displayName="BackPack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="herob, MCreator"

[[dependencies.backpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




